### ISSUE TITLE
Mitarbeiter kann Urlaub beantragen

### ISSUE THREAD

**Issue by querqueq** [sese-xp3-ws2017/sese-xp3-ws2017#38]
Als Mitarbeiter kann man für einen bestimmten Zeitraum Urlaub beantragen.

**Comment by Alwaysgone** [comment]
Vacations could be displayed as calendar to make it accessible for both normal staff members and managers without giving normal staff members the possibility to change anything.

**Comment by querqueq** [comment]
Done during #45
