### ISSUE TITLE
Continious Deployment aufsetzten

### ISSUE THREAD

**Issue by querqueq** [sese-xp3-ws2017/sese-xp3-ws2017#5]

**Comment by lkerck** [comment]
Travis is currently building every pushed tag and deploying it to github releases. Last missing step: somehow get that file onto a server ;)

**Comment by lkerck** [comment]
CD with heroku implementing

**Comment by lkerck** [comment]
https://sese-xp3-ws2017.herokuapp.com & https://sese-xp-ws2017-dev.herokuapp.com
