### ISSUE TITLE
Format und Modus für Entwickler-Tagebuch definieren

### ISSUE THREAD

**Issue by querqueq** [sese-xp3-ws2017/sese-xp3-ws2017#8]
**Anforderungen**

* Format muss einheitlich über alle Entwickler hinaus sein, damit wir im Endreport die Tagebücher einfach einfügen können.
* Modus definiert, welcher festlegt wann man einen Tagebucheintrag erstellen soll.

**DOD**
Jeder Entwickler ist informiert über das Format und den Modus für das Entwickler-Tagebuch anhand eines Beispiels.

**Comment by Alwaysgone** [comment]
Added document to describe developer diary
